---
- name: Setting custom fact
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Create Custom Facts Directory
      ansible.builtin.file:
        path: "/etc/ansible/facts.d"
        state: directory
        mode: "0755"

    - name: Set Custom Fact
      ansible.builtin.copy:
        content: "foo: passed"
        dest: "/etc/ansible/facts.d/custom.fact"
        mode: "0644"

    - name: Gather updated facts
      ansible.builtin.setup:
