---
- name: Setting custom fact
  hosts: all
  gather_facts: true

  tasks:
    - name: Set Fact for Testing
      set_fact:
        test_fact: "justatest"
        cacheable: true

    - name: Gather updated facts
      ansible.builtin.setup:
